---
title: "dataset-malware-analysis"
author: "Rodrigo Bonifácio et al."
date: '2022-10-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=5, fig.height=5, fig.path='./figures/', dev=c('png', 'pdf'))

setwd(".")

library(sqldf)
library(xtable)
```
# Loading and cleaning up the datasets

```{r fullDataSet}
full_ds <- read.csv("final_dataset_TSE.csv", head=T, sep=',')
small_ds <- read.csv("samples_DL_final_ds.csv", head=T, sep=',')


colnames(full_ds)

nrow(full_ds)
nrow(small_ds)

# "sha256"      "family"      "malware"     "apidetected" "similarity"
```

## Computing basic statistics for similarity 

```{r similarityCDS}
summary(small_ds$similarity)
sd(small_ds$similarity)

summary(full_ds$similarity)
sd(full_ds$similarity)

sqldf("select count(*) from full_ds where similarity = 0")

sqldf("select count(*) from full_ds where similarity < 0.25")
sqldf("select count(*)  from full_ds where similarity >= 0.25 and similarity < 0.5")
sqldf("select count(*)  from full_ds where similarity >= 0.5 and similarity < 0.75")
sqldf("select count(*)  from full_ds where similarity >= 0.75")
sqldf("select count(*)  from full_ds where similarity >= 0.90")

```

### Comparing the similarity scores (complete and small datasets)

```{r similarityComparison}
summary(small_ds$similarity)
summary(full_ds$similarity)

sd(small_ds$similarity)
sd(full_ds$similarity)


sds <- sqldf("select similarity, 'Small Dataset' as dataset from small_ds") 
cds <- sqldf("select similarity, 'Complete Dataset' as dataset from full_ds") 

ds <- rbind(sds, cds)

ds$dataset <- factor(ds$dataset , levels=c("Small Dataset", "Complete Dataset"))


boxplot(similarity~dataset, data = ds, xlab="Datasets", ylab="Similarity Score", col = c("gray"), outline=F)
```
### Logistic regression (on similarity)

```{r glm}


#s1 <- sqldf("select ds.*, 'True' as h1 
#             from full_ds ds 
#             where (malware = 'True' and apidetected = 'True') or 
#                   (malware = 'False' and apidetected = 'False')")

s1 <- sqldf("select ds.*, 'True' as h1 
             from full_ds ds 
             where ((family_repackaged <> 'NULL' and family_repackaged <> 'noIdentify') and method_in_diff <> '0')")

s2 <- sqldf("select ds.*, 'False' as h1 
             from full_ds ds
             where ((family_repackaged <> 'NULL' and family_repackaged <> 'noIdentify') and method_in_diff = '0') or 
                   ((family_repackaged = 'NULL' or family_repackaged = 'noIdentify') and method_in_diff <> '0')")

ds <- rbind(s1, s2)


ds$h1 <- as.factor(ds$h1)

# cor.test(ds$h1, ds$similarity)

nrow(ds)

sqldf("select h1, count(*) from ds group by h1")

model <- glm(h1~similarity, data=ds, family = "binomial")

summary(model)
```
### Clustering assessment (on similarity)

```{r clusterinigSimilarity}
set.seed(123)

km.res <- kmeans(ds$similarity, 10)

print(km.res)

dd <- cbind(ds, cluster = km.res$cluster)

head(dd)

s1 <- sqldf("select cluster, count(*) as total from dd group by cluster")
s2 <- sqldf("select cluster, count(*) as hits from dd where h1 = 'True' group by cluster")

dd = merge(s1, s2)

dd["Percent"] = dd$hits * 100 / dd$total

dd 


## 1  0.9078245
## 2  0.6777151
## 3  0.9438909
## 4  0.8751277
## 5  0.7967092
## 6  0.9877759
## 7  0.9976499
## 8  0.9667710
## 9  0.5547798
## 10 0.0926632

cs = data.frame("cluster" = c(1,2,3,4,5, 6, 7, 8, 9, 10), 
                "averageSimilarity" = c(0.90, 0.67, 0.94, 0.87, 0.79,0.98,0.99,0.96, 0.55, 0.09))

cs = merge(dd, cs)

colnames(cs)

xtable(sqldf("select cluster, averageSimilarity, total, hits, percent 
              from cs 
              order by averageSimilarity"))


km.res <- kmeans(ds$similarity, 5)

print(km.res)

dd <- cbind(ds, cluster = km.res$cluster)

head(dd)

s1 <- sqldf("select cluster, count(*) as total from dd group by cluster")
s2 <- sqldf("select cluster, count(*) as hits from dd where h1 = 'True' group by cluster")

dd = merge(s1, s2)

dd["Percent"] = dd$hits * 100 / dd$total

dd 

## 1 0.0409438
## 2 0.9878021
## 3 0.7776560
## 4 0.5158275
## 5 0.8988103

cs = data.frame("cluster" = c(1,2,3,4,5), 
                "averageSimilarity" = c(0.04, 0.98, 0.77, 0.51, 0.89))

cs = merge(dd, cs)

colnames(cs)

xtable(sqldf("select cluster, averageSimilarity, total, hits, percent 
              from cs 
              order by averageSimilarity"))

```
### Similarity Assessment (Gappusin Family)

```{r, similarityGappusin}
# Gappusin family

gappusin <- sqldf("select * from full_ds where family_repackaged =  'gappusin'")

summary(gappusin$similarity)
sd(gappusin$similarity)
hist(gappusin$similarity, main="", xlab="Similarity Score", ylab="Frequency", col = c("gray"))


```

### Logistic regression (on similarity)

```{r glm}


#s1 <- sqldf("select ds.*, 'True' as h1 
#             from full_ds ds 
#             where (malware = 'True' and apidetected = 'True') or 
#                   (malware = 'False' and apidetected = 'False')")

s1 <- sqldf("select ds.*, 'True' as h1 
             from full_ds ds 
             where ((family_repackaged is not null and family_repackaged <> 'noIdentify') and method_in_diff <> '0')")



s2 <- sqldf("select ds.*, 'False' as h1 
             from full_ds ds
             where ((family_repackaged is not null and family_repackaged <> 'noIdentify') and method_in_diff = '0') or 
                   ((family_repackaged is null or family_repackaged = 'noIdentify') and method_in_diff <> '0')")



ds <- rbind(s1, s2)


ds$h1 <- as.factor(ds$h1)

# cor.test(ds$h1, ds$similarity)

nrow(ds)

sqldf("select h1, count(*) from ds group by h1")

model <- glm(h1~similarity, data=ds, family = "binomial")

summary(model)
```